### ISSUE TITLE
focus with `HookSelect`

### ISSUE THREAD

**Issue by bryanprimus** [adiathasan/mui-react-hook-form-plus#1]
If the value of select is invalid caused by validation. and we press submit button. the select component doesn't get focused. 

https://mui-react-hook-form-plus.vercel.app/?path=/docs/hookselect--hookselect

sorry but haven't checked the code. perhaps this is caused by `ref` not being passed properly

**Comment by adiathasan** [comment]
Hey [bryantobing12](https://github.com/bryantobing12) thanks for trying it out. 

Yeah, `ref` is the issue I see here.

Hopefully will be fixed by the next release.

**Comment by adiathasan** [comment]
Hey [bryantobing12](https://github.com/bryantobing12),

Great fix buddy 🎉
