### ISSUE TITLE
upload file component is missing ?

### ISSUE THREAD

**Issue by nsit8919** [adiathasan/mui-react-hook-form-plus#10]
Hi 

you have created a very good library which helps a lot  but I think there is a missing component .  File upload component . is there any example of file upload ?

**Comment by adiathasan** [comment]
Hey,

Thanks for the suggestion. I'm marking it down. You can expect in the next release

**Comment by adiathasan** [comment]
Just star/subscribe to the repo you will get the notification if a  new release is made
