### ISSUE TITLE
Published NPM Package is Empty

### ISSUE THREAD

**Issue by RedcedarGeoff** [adiathasan/mui-react-hook-form-plus#11]
Current version of the published package, `1.3.3`, is empty, the `dist` folder does not exist. See [here](https://www.npmjs.com/package/mui-react-hook-form-plus?activeTab=code)

[Here](https://www.npmjs.com/package/mui-react-hook-form-plus/v/1.3.2?activeTab=code) is the previous version, with the `dist` folder present and accounted for.

**Comment by adiathasan** [comment]
OOPS Just got busted. Thanks for catching 

I will be fixing it now.

**Comment by adiathasan** [comment]
Updated to 1.3.4 _>
