### ISSUE TITLE
why variable value is not updated inside function but update outside function. in react js?

### ISSUE THREAD

**Issue by naveennsit** [adiathasan/mui-react-hook-form-plus#12]
I am sending a function as props in reactjs .I have one state "form submitted" or "not submitted". I am getting wrong output (console output) inside the function . don't know why ? But outside function I am getting correct value.

here is my code
https://codesandbox.io/s/cool-dawn-0uu62q?file=/src/nested.tsx

    const NestedComponent = () => {
      const { registerState, formState } = useHookFormContext();
      console.log(formState.isSubmitted, "outside");
    
      return (
        <>
          <CustomApi
            key={"abc"}
            options={[]}
            onChange={() => {
              console.log(formState.isSubmitted, "inside");
              console.log("sss");
            }}
          />
        </>
      );
    };

steps to reproduce bug

 - run application . see console it will show **false** which is correct.
 - Click submit button . see console it will show **true** which is correct.
 - Now change the dropdown value .see console it will show **false** value which is incorrect correct. why is showing different value

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/z454V.png

is it closure issue ???

**Comment by adiathasan** [comment]
Fixed with this release - `v1.3.5` 

Forgot to reassign the `onChangeRef` in each render cycle. Hence closure got the prev value

```diff

+ const onChangeRef = React.useRef(onChange);
+ /**
+  * we update the ref on every render
+  */
+ onChangeRef.current = onChange;

```

example: https://codesandbox.io/s/quizzical-nova-ur0rv8?file=/src/nested.tsx
