### ISSUE TITLE
file upload component with preview

### ISSUE THREAD

**Issue by naveennsit** [adiathasan/mui-react-hook-form-plus#14]
Can we use react-dropzone in react-hook-form-plus. can we convert below example using react-hook-form-plus
https://www.npmjs.com/package/react-dropzone

Instead of using "register" can we use registerState ?

https://codesandbox.io/s/react-hook-form-uploadfile-with-thumbnail-preview--drag-and-drop-forked-8n1jh9?file=/src/FileInput.jsx

I tried this but it stop working..

**Comment by naveennsit** [comment]
I tried like this https://codesandbox.io/s/react-hook-form-uploadfile-with-thumbnail-preview--drag-and-drop-forked-pm9fig?file=/src/FileInput.jsx

**Comment by adiathasan** [comment]
You can follow the below example

https://codesandbox.io/s/react-hook-form-uploadfile-with-thumbnail-preview--drag-and-drop-forked-4rldnk?file=/src/FileInput.jsx

**Comment by naveennsit** [comment]
@adiathasan  but it is not accepting multiple file . I am sending multiple = true

**Comment by naveennsit** [comment]
previously it was working fine ,

**Comment by adiathasan** [comment]
It's working for me

<img width="1411" alt="image" src="https://github.com/adiathasan/mui-react-hook-form-plus/assets/61478071/f0fe90c8-ff36-4317-8a70-95ecc41b3b7c">

**Comment by naveennsit** [comment]
any idea why my code sandbox not working https://codesandbox.io/s/react-hook-form-uploadfile-with-thumbnail-preview--drag-and-drop-forked-8n1jh9?file=/src/FileInput.jsx
