### ISSUE TITLE
why multiple preview image not working ?

### ISSUE THREAD

**Issue by naveennsit** [adiathasan/mui-react-hook-form-plus#15]
Hi
I am using react-dropzone with final-form-plus. But multiple preview is not working . I tried multiple ways . None of them work

here is my code
https://codesandbox.io/s/react-hook-form-uploadfile-with-thumbnail-preview--drag-and-drop-forked-8n1jh9?file=/src/FileInput.jsx:0-2624

import React, { useCallback } from "react";
import { useDropzone } from "react-dropzone";
import { useHookForm } from "mui-react-hook-form-plus";
import { useWatch } from "react-hook-form";

const FileInput = (props) => {
  const { name, label = name, mode = "update" } = props;

  const { register, control, setValues } = useHookForm({
    defaultVaues: {
      files: []
    }
  });

  const files = useWatch({
    control,
    name: "files"
  });

  const onDrop = useCallback(
    (droppedFiles) => {
      console.log(droppedFiles, "filesfiles");
      console.log(files, "files");
      let o = files ? [...files, ...droppedFiles] : droppedFiles;
      console.log(o, "oooo");
      setValues({
        files: o
      });
    },
    [setValues]
  );

  const { getRootProps, getInputProps, isDragActive } = useDropzone({
    onDrop,
    accept: props.accept
  });

  return (
    <div style={{ padding: "100px" }}>
      <label
        className="block text-gray-700 text-sm font-bold mb-2 capitalize"
        htmlFor={name}
      >
        {label}
      </label>

      <div {...getRootProps()}>
        <input
          {...register("files")}
          {...props}
          className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
          id={name}
          {...getInputProps()}
        />

        <div
          className={
            "w-full p-2 border border-dashed border-gray-900 " +
            (isDragActive ? "bg-gray-400" : "bg-gray-200")
          }
        >
          <p className="text-center my-2">Drop the files here ...</p>
          {!!files?.length && (
            <div className="grid gap-1 grid-cols-4 mt-2">
              {files.map((file, i) => {
                return (
                  <div key={file.name}>
                    <img
                      src={URL.createObjectURL(file)}
                      alt={file.name}
                      style={{ width: "100px", height: "100px" }}
                    />
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        console.log(files);
                        setValues({
                          files: files.filter((f, _i) => _i !== i)
                        });
                      }}
                    >
                      delete
                    </button>
                  </div>
                );
              })}
            </div>
          )}
          {files?.length}lenn
        </div>
      </div>
    </div>
  );
};

export default FileInput;

**Comment by adiathasan** [comment]
Here is an working examle

https://codesandbox.io/s/react-hook-form-uploadfile-with-thumbnail-preview--drag-and-drop-forked-4cxyi8?file=/src/FileInput.jsx
