### ISSUE TITLE
is there any way to access getValue , setvalues, setValues on parent component 

### ISSUE THREAD

**Issue by naveennsit** [adiathasan/mui-react-hook-form-plus#16]
Hi
I am trying to generate form using JSON .I am able to render that form using JSON. But I am trying to access all method on parent component getValue , setvalues, setValues . is it possible ?

here is my code
https://codesandbox.io/s/intelligent-lake-6h6cdq?file=/src/formbuilder.tsx

parent component

`export default function App() {
  //const methods = useHookForm();
  const onChange = () => {
    //console.log("000000", methods?.getValues());
// am trying 
    //methods.setValue("firstName", "asdasd");
  };

  // const { registerState, handleSubmit } = methods;

  const onSubmit = (data: any) => {
    console.log(data);
  };
  return (
    <FormBuilder
      jsonSchema={json}
      defaultValue={defaultValue}
      onSubmitHandler={onSubmit}
      functionHandler={{
        onChange: onChange
      }}
    />
  );
}`

On Dropdown change i am calling on change method . I want to set some value using setvalue or setvalues function is it possible

  const onChange = () => {
    //console.log("000000", methods?.getValues());
// am trying 
    //methods.setValue("firstName", "asdasd");
  };

**Comment by adiathasan** [comment]
Here is the example,

https://codesandbox.io/s/sweet-dhawan-3qnrng?file=/src/formbuilder.tsx
