### ISSUE TITLE
date time picker rules  not working

### ISSUE THREAD

**Issue by naveennsit** [adiathasan/mui-react-hook-form-plus#18]
Hi Adiat
Date time picker component rules not working..
required and validate both rules are not working.
here is my code
https://codesandbox.io/p/sandbox/asdkad-fqpy53?file=%2Fsrc%2FApp.tsx%3A26%2C24

**Comment by naveennsit** [comment]
`import "./styles.css";
import { LocalizationProvider } from "@mui/x-date-pickers/LocalizationProvider";
import { AdapterDateFns } from "@mui/x-date-pickers/AdapterDateFns";
import { Button } from "@mui/material";

import {
  HookDesktopDateTimePicker,
  useHookForm,
} from "mui-react-hook-form-plus";

export default function App() {
  const { registerState, handleSubmit } = useHookForm({
    defaultValues: {
      trialEndsAt: null,
    },
  });
  const onSubmit = (_data) => {
    alert(_data);
  };
  return (
    <LocalizationProvider dateAdapter={AdapterDateFns}>
      <form onSubmit={handleSubmit(onSubmit)}>
        <HookDesktopDateTimePicker
          {...registerState("trialEndsAt")}
          rules={{
            required: {
              value: true,
              message: "Required",
            },
            validate: {
              min: (value) => {
                console.log("sssss");
                if (value < new Date()) {
                  return "Must be greater than today";
                }
              },
            },
          }}
          desktopDateTimePickerProps={{
            label: "Desktop",
          }}
          textFieldProps={{
            label: "Desktosssp",
            helperText: "Helper text",
          }}
        />
        <br />
        <Button sx={{ marginTop: 2 }} type="submit" variant="contained">
          Submit
        </Button>
      </form>
    </LocalizationProvider>
  );
}
`

**Comment by naveennsit** [comment]
https://stackblitz.com/edit/vitejs-vite-vyuaqs?file=src%2Findex.css,src%2FApp.css&terminal=dev

**Comment by adiathasan** [comment]
Sorry man. Was busy. Will look into it soon

**Comment by naveennsit** [comment]
Ignore it's fixed
