### ISSUE TITLE
unmet peerDependencies with React 18

### ISSUE THREAD

**Issue by bryanprimus** [adiathasan/mui-react-hook-form-plus#3]
![image](https://user-images.githubusercontent.com/46083126/193440023-9be7b05d-845d-4ab1-81c4-2de3737b0a14.png)

I'll open a PR If it's just updating peerDependencies listed in [package.json](https://github.com/adiathasan/mui-react-hook-form-plus/blob/master/package.json)

**Comment by adiathasan** [comment]
Hey [bryantobing12](https://github.com/bryantobing12), 

I think below is the perfect solution,
See, https://nodejs.org/es/blog/npm/peer-dependencies/

```diff
-   "react": "^17.0.1 || ^18.0.0",
+   "react": ">= 17.0.1",
```

What do you think?

**Comment by bryanprimus** [comment]
we can do that. but it will allow newer major version that we are not sure this package will support or not break in that new major version

**Comment by adiathasan** [comment]
Ok removed fewer of them and only `mui` requires to be 5.0.0 and greater
