### ISSUE TITLE
Support for DesktopDatePicker

### ISSUE THREAD

**Issue by esskar** [adiathasan/mui-react-hook-form-plus#5]
Hello,

thanks for the library, it looks great.
Is there a way to integrate `DesktopDatePicker` from https://mui.com/x/api/date-pickers/desktop-date-picker/

Any hints would be great.

**Comment by adiathasan** [comment]
Thank you for your suggestion. 

Yeah, the next release will be with the date picker hopefully.

**Comment by adiathasan** [comment]
Added DatePicker as you wanted 
Time Picker & DateRange Picker coming soon

> ### DatePicker
1.  `<HookDatePicker />`
2.  `<HookStaticDatePicker />`
3.  `<HookDesktopDatePicker />`
4.  `<HookMobileDatePicker />`
