### ISSUE TITLE
Module not found: Can't resolve 'mui-react-hook-form-plus'

### ISSUE THREAD

**Issue by strangeliu** [adiathasan/mui-react-hook-form-plus#6]
I have installed mui, react-hook-form, @mui/x-date-pickers and mui-react-hook-form-plus.
and mui-react-hook-form-plus folder exist in node_modules,
but when compile, it will failed with `Module not found: Can't resolve 'mui-react-hook-form-plus'`

**Comment by strangeliu** [comment]
<img width="1237" alt="Screenshot 2022-11-02 at 17 07 50" src="https://user-images.githubusercontent.com/5244588/199449787-03854cab-d91e-4ff8-ae5e-7844a2bd3a36.png">
The define link is work, only compile failed.
I noticed the format of index file is `d.ts`, will it be ignored when compile?

**Comment by adiathasan** [comment]
Yes, it will be ignored `d.ts` file is `type-def` file.

And can you please elaborate more on what is actually happening? Is it working in development or it's not even compiling?

**Comment by adiathasan** [comment]
I'm using `vite` it's working fine 🚀 

```json
  "dependencies": {
    "@emotion/react": "^11.10.4",
    "@emotion/styled": "^11.10.4",
    "@mui/icons-material": "^5.10.6",
    "@mui/material": "^5.10.5",
    "@mui/x-date-pickers": "^5.0.4",
    "mui-react-hook-form-plus": "^1.3.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-hook-form": "^7.35.0",
    "react-hook-form-mui": "^5.7.2"
  },
```
