### ISSUE TITLE
Type for `registerState` Fn in `mui-react-hook-form-plus`?

### ISSUE THREAD

**Issue by nsit8919** [adiathasan/mui-react-hook-form-plus#7]
I am following below links to create simple example

https://github.com/adiathasan/mui-react-hook-form-plus

or Live example

https://mui-react-hook-form-plus.vercel.app/?path=/docs/form-context--hookformprovider
I am getting this error
**Property 'registerState' does not exist on type '{}'.ts(2339)**

I don't want to use **any**  keyword .Is there any type of **registerState** ?

here is my code
https://codesandbox.io/s/mystifying-sky-6b2gs8?file=/src/autpcomplete.tsx

    const Accordion: React.FC = ({ registerState }) => {
      return (
        <HookAutoComplete
          {...registerState("movie")}
          autocompleteProps={{
            options: top100Films,
            autoHighlight: true,
            isOptionEqualToValue: ({ label }: FilmOption, value) =>
              label === value.label
          }}
          textFieldProps={{
            label: "Movie",
            placeholder: "The..."
          }}
          gridProps={{
            xs: 12
          }}
          rules={{
            required: {
              message: "Required",
              value: true
            }
          }}
        />
      );
    };

when I go to github repo I saw below code

	https://github.com/adiathasan/mui-react-hook-form-plus/blob/master/src/lib/react-hook-form/hooks/useHookForm.ts
**see code**

   

     const registerState = useCallback(
        		(name: FieldPath<TFieldValues>) => {
        			return {
        				control,
        				formState,
        				name,
        				setValue,
        				trigger,
        			};
        		},
        		[control, formState, setValue, trigger]
        	);

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/697oo.png

**Comment by adiathasan** [comment]
Hi @nsit8919,

Thank you for reaching out to me.

you can use `UseHookFormRegisterFn<YourInterface>` as a type for `registerState` function.

```tsx
interface Props {
  registerState: UseHookFormRegisterFn<{ movie: string }>;
}

const Accordion: React.FC<Props> = ({ registerState }) => {

   ......

}

```

I have edited the code-sandbox link that you have provided.

Here is the link:

https://codesandbox.io/s/wonderful-mirzakhani-qjmotk?file=/src/autpcomplete.tsx

**Comment by adiathasan** [comment]
Closing the issue as it is nothing to deal with bugs.

**Comment by nsit8919** [comment]
@adiathasan thanks for providing answer
