### ISSUE TITLE
Type-safe `useHookFormContext` 

### ISSUE THREAD

**Issue by nsit8919** [adiathasan/mui-react-hook-form-plus#9]
i am using **react hook form** to build demo application.I am using `usefieldarray` to append rows.

https://react-hook-form.com/api/usefieldarray/

but i am getting typescript error 

**[![Property 'number' does not exist on type 'Record<"id", string>' in react js][1]][1]** 

I already defined interface

    export interface InitiateHoldModel {
      checked: boolean | null;
      containers: Array<ContainerOnHold> | null;
    }
    export interface ContainerOnHold {
      checked: boolean;
      number: string;
      size: string;
    }

Here is my code
https://codesandbox.io/s/priceless-kowalevski-c0qjmh?file=/src/ReleaseFields.tsx:0-805

    import { HookCheckBox, useHookFormContext } from "mui-react-hook-form-plus";
    import { useFieldArray } from "react-hook-form";
    
    export default function ReleaseFields(): JSX.Element {
      const { registerState, control } = useHookFormContext();
      const prependKey = "containers";
      const { fields } = useFieldArray({
        control,
        name: prependKey
      });
      return (
        <>
          <HookCheckBox {...registerState("checked")} />
          <label>B344332</label>
          {fields.length > 0 && (
            <ul>
              {fields.map((item, index) => (
                <li key={index}>
                  <HookCheckBox
                    {...registerState(`${prependKey}[${index}].checked`)}
                  />
                  {item.number}
                  {item.size}
                </li>
              ))}
            </ul>
          )}
        </>
      );
    }

  [1]: https://i.stack.imgur.com/zTO1Z.png

**Comment by adiathasan** [comment]
You have to pass the generics to the `useHookFormContext`

Example:
```tsx
export default function ReleaseFields(): JSX.Element {
  const { registerState, control } = useHookFormContext<InitiateHoldModel>();
  
  const { fields } = useFieldArray({
    control,
    name: 'containers'
  });
 
  return (
    <>
      <HookCheckBox {...registerState("checked")} />
      <label>B344332</label>
      {fields.length > 0 && (
        <ul>
          {fields.map((item, index) => (
            <li key={index}>
              <HookCheckBox
                {...registerState(`containers.${index}.checked`)}
              />
              {item.number}
              {item.size}
            </li>
          ))}
        </ul>
      )}
    </>
  );
}

```
Now you are good to go...

Example code here:

https://codesandbox.io/s/lucid-bash-5lrroq?file=/src/ReleaseFields.tsx

**Comment by adiathasan** [comment]
Closing it
